import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        "bs-bg": "#0d1e2c",
        "bs-surface": "#132638",
        "bs-raised": "#1a3148",
        "bs-overlay": "#213d58",
        "bs-border": "#1e3f5a",
        "bs-border-soft": "#162f45",
        "bs-teal": "#00d4aa",
        "bs-amber": "#f5a623",
        "bs-coral": "#ff6b6b",
        "bs-success": "#34d399",
        "bs-warning": "#fbbf24",
        "bs-info": "#60a5fa",
        "bs-violet": "#a78bfa",
        "bs-text": "#e8f4f0",
        "bs-text-sub": "#9abcb0",
        "bs-text-muted": "#5a8070",
        bg: "rgb(var(--color-bg) / <alpha-value>)",
        text: "rgb(var(--color-text) / <alpha-value>)",
        "text-muted": "rgb(var(--color-text-muted) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        "surface-1": "rgb(var(--color-surface-1) / <alpha-value>)",
        "surface-2": "rgb(var(--color-surface-2) / <alpha-value>)",
        "surface-3": "rgb(var(--color-surface-3) / <alpha-value>)",
        "brand-purple": "rgb(var(--color-brand-purple) / <alpha-value>)",
        "brand-orange": "rgb(var(--color-brand-orange) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        error: "rgb(var(--color-error) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        "teks-rc1": "rgb(var(--teks-rc1) / <alpha-value>)",
        "teks-rc2": "rgb(var(--teks-rc2) / <alpha-value>)",
        "teks-rc3": "rgb(var(--teks-rc3) / <alpha-value>)",
        "teks-rc4": "rgb(var(--teks-rc4) / <alpha-value>)",
        "teks-rc5": "rgb(var(--teks-rc5) / <alpha-value>)",
        "teks-rc6": "rgb(var(--teks-rc6) / <alpha-value>)",
        // BioSpark design system tokens (bs-*)
        bs: {
          bg:          "var(--bs-bg)",
          surface:     "var(--bs-surface)",
          raised:      "var(--bs-raised)",
          overlay:     "var(--bs-overlay)",
          border:      "var(--bs-border)",
          "border-soft": "var(--bs-border-soft)",
          teal:        "var(--bs-teal)",
          "teal-dim":  "var(--bs-teal-dim)",
          amber:       "var(--bs-amber)",
          "amber-dim": "var(--bs-amber-dim)",
          coral:       "var(--bs-coral)",
          "coral-dim": "var(--bs-coral-dim)",
          success:     "var(--bs-success)",
          warning:     "var(--bs-warning)",
          danger:      "var(--bs-danger)",
          info:        "var(--bs-info)",
          text:        "var(--bs-text)",
          "text-sub":  "var(--bs-text-sub)",
          "text-muted":"var(--bs-text-muted)",
        },
      },
      spacing: {
        18: "4.5rem",
      },
      borderRadius: {
        xs: "0.375rem",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
      },
      fontFamily: {
        sans: ["Outfit", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        display: ["var(--font-display)", "sans-serif"],
        ui:   ["var(--bs-font-ui)", "sans-serif"],
        mono: ["var(--bs-font-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        xs: [
          "var(--text-xs-size)",
          { lineHeight: "var(--text-xs-line)", letterSpacing: "0em" },
        ],
        sm: [
          "var(--text-sm-size)",
          { lineHeight: "var(--text-sm-line)", letterSpacing: "0em" },
        ],
        base: [
          "var(--text-base-size)",
          { lineHeight: "var(--text-base-line)", letterSpacing: "0em" },
        ],
        lg: [
          "var(--text-lg-size)",
          { lineHeight: "var(--text-lg-line)", letterSpacing: "-0.005em" },
        ],
        xl: [
          "var(--text-xl-size)",
          { lineHeight: "var(--text-xl-line)", letterSpacing: "-0.01em" },
        ],
        "2xl": [
          "var(--text-2xl-size)",
          { lineHeight: "var(--text-2xl-line)", letterSpacing: "-0.012em" },
        ],
        "3xl": [
          "var(--text-3xl-size)",
          { lineHeight: "var(--text-3xl-line)", letterSpacing: "-0.015em" },
        ],
        "4xl": [
          "var(--text-4xl-size)",
          { lineHeight: "var(--text-4xl-line)", letterSpacing: "-0.02em" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
