export const MOCK_ASSIGNMENTS = [
  {
    id: "assignment-1",
    title: "Unit 1 Check-In",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "assignment-2",
    title: "Photosynthesis Quiz",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "assignment-3",
    title: "Genetics Practice",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "assignment-4",
    title: "Ecology Final",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_RESPONSES: Record<string, any[]> = {
  "assignment-1": [
    {
      itemId: "bio-1",
      studentId: "stu-1",
      studentName: "Ava",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-2",
      studentId: "stu-1",
      studentName: "Ava",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-1",
      studentId: "stu-2",
      studentName: "Ben",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
  ],
  "assignment-2": [
    {
      itemId: "bio-3",
      studentId: "stu-1",
      studentName: "Ava",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-3",
      studentId: "stu-2",
      studentName: "Ben",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
  ],
  "assignment-3": [
    {
      itemId: "bio-1",
      studentId: "stu-1",
      studentName: "Ava",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-2",
      studentId: "stu-1",
      studentName: "Ava",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-4",
      studentId: "stu-1",
      studentName: "Ava",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-1",
      studentId: "stu-2",
      studentName: "Ben",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-2",
      studentId: "stu-2",
      studentName: "Ben",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-4",
      studentId: "stu-2",
      studentName: "Ben",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-5",
      studentId: "stu-3",
      studentName: "Cara",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-5",
      studentId: "stu-4",
      studentName: "Dylan",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
  ],
  "assignment-4": [
    {
      itemId: "bio-6",
      studentId: "stu-1",
      studentName: "Ava",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-6",
      studentId: "stu-2",
      studentName: "Ben",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-7",
      studentId: "stu-3",
      studentName: "Cara",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-7",
      studentId: "stu-4",
      studentName: "Dylan",
      isCorrect: false,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-8",
      studentId: "stu-5",
      studentName: "Ella",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-9",
      studentId: "stu-5",
      studentName: "Ella",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
    {
      itemId: "bio-10",
      studentId: "stu-5",
      studentName: "Ella",
      isCorrect: true,
      submittedAt: new Date().toISOString(),
    },
  ],
};
